config/routes.rb
Rails.application.routes.draw do
  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users, :controllers => { registrations: "registrations"} do
    resources :events
  end
  resources :events
  root to: 'events#index'
  
  resources :enrollments, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  enum status: { invited: 0, accepted: 1 }
  belongs_to :user, optional: true
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', optional: true
  validates :name, :date, presence: true
  has_many :enrollments, dependent: :delete_all
  has_many :attendees, through: :enrollments, source: :user, dependent: :delete_all
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, inverse_of: :creator
  has_many :enrollments
  has_many :attended_events, through: :enrollments, source: :event
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrollment_controller.rb
class EnrollmentController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    enrollment = Enrollment.new(event_id: event.id, user_id: params[:user_id])

    if enrollment.save
      enrollment.invited!
      flash[:success] = 'Invitation sent to user'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Something went wrong...'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    enrollment = Enrollment.find(params[:id])
    if current_user == event.creator
      enrollment.destroy
      flash[:success] = 'Invitation removed'
    else
      enrollment.invited!
      flash[:alert] = 'Something went wrong...'
    end

    redirect_to root_path
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def create
    event = Event.find(params[:event_id])
    enrollment = Enrollment.new(event_id: event.id, user_id: params[:user_id])

    if enrollment.save
      enrollment.invited!
      flash[:success] = 'Invitation sent to user'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Something went wrong...'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    enrollment = Enrollment.find(params[:id])
    if current_user == event.creator
      enrollment.destroy
      flash[:success] = 'Invitation removed'
    else
      enrollment.invited!
      flash[:alert] = 'Enrollment cancelled!'
    end

    redirect_to root_path
  end

  def update
    @event = Event.find(params[:event_id])
    @enrollment = Enrollment.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @enrollment&.invited?
      @enrollment.accepted!
      flash[:notice] = "Thank you for signing up for the '#{@event.name}'!"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create show]

  # GET /events or /events.json
  def index
    # @user = User.find params[:user_id]
    @events = Event.all.order('date DESC')
    @past_events = @events.past
    @upcoming_events = @events.upcoming
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /events/1 or /events/1.json

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :date, :location, :description)
  end
end

app/controllers/registrations_controller.rb
# rubocop:disable Layout/EndOfLine
class RegistrationsController < Devise::RegistrationsController
  private

  def index
    @user = User.all
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end
# rubocop:enable Layout/EndOfLine

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_btn
    return render partial: 'layouts/alerts' if flash[:alert]
  end

  def notice_btn
    return render partial: 'layouts/notice' if flash[:notice]
  end
end

app/helpers/enrollment_helper.rb
module EnrollmentHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def create_event_btn
    out = ''
    out << link_to('New Event', new_event_path, class: 'me-3 py-2 text-dark text-decoration-none') if user_signed_in?
    out.html_safe
  end

  def profile_btn
    return render partial: 'events/profile' if user_signed_in?
  end
end

app/helpers/registrations_helper.rb
# rubocop:disable Layout/LineLength, Layout/EndOfLine
module RegistrationsHelper
  def current_user_btn
    out = ''
    if user_signed_in?
      out << link_to(current_user.name, edit_user_registration_path, class: 'me-3 py-2 text-dark text-decoration-none')
    end
    out.html_safe
  end

  def sign_out_btn
    out = ''
    if user_signed_in?
      out << link_to('Sign Out', destroy_user_session_path, method: :delete, class: 'me-3 py-2 text-dark text-decoration-none')
    end
    out.html_safe
  end

  def sign_up_btn
    out = ''
    unless user_signed_in?
      out << link_to('Sign Up', new_user_registration_path, class: 'me-3 py-2 text-dark text-decoration-none')
    end
    out.html_safe
  end

  def log_in_btn
    out = ''
    unless user_signed_in?
      out << link_to('Log In', new_user_session_path, class: 'me-3 py-2 text-dark text-decoration-none')
    end
    out.html_safe
  end
end
# rubocop:enable Layout/LineLength, Layout/EndOfLine

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_accepted.html.erb
<ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1"">
  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
       Accepted: <%= User.find(@event.enrollments.accepted.map {|en_user| en_user.user_id }).count %> <b class="caret"></b>
      </a>
      <% if User.find(@event.enrollments.accepted.map {|en_user| en_user.user_id }).any? %>
      <ul class="dropdown-menu">
      <% User.find(@event.enrollments.accepted.map { |en_user| en_user.user_id }).each do |user| %>
        <li>
          <%= user.name %>
        </li>
      <% end %>
      </ul>
      <% end %>
  </li>
</ul>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-12 col-md-6">
    <%= form.label :name, class:'form-label' %>
    <%= form.text_field :name, class:'form-control', id:'event_name' %>
  </div>

  <div class="field col-12 col-md-6 my-2">
    <%= form.label :date, class:'form-label' %>
    <%= form.date_select :date, class:'form-control', id: 'date' %>
  </div>

  <div class="field col-12 col-md-6">
    <%= form.label :location, class:'form-label' %>
    <%= form.text_field :location, class:'form-control', id:'location' %>
  </div>

  <div class="field col-12 col-md-6">
    <%= form.label :description, class:'form-label' %>
    <%= form.text_area :description, class:'form-control', id:'description' %>
  </div>

  <div class='btn btn-light my-2'>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_invite.html.erb
<% if @event.creator == current_user %>
    <%= button_to  'Invite member', users_path, params: { :event_id => @event.id }, method: :get, class:"btn btn-dark btn-lg" %>
<% else %>
    <% enrollment = current_user.enrollments.find_by(event_id: @event.id) %>
    <% if  enrollment %>
       <%= button_to  'Cancel', enrollment_path(id: enrollment.id, event_id: @event.id, user_id: current_user.id), method: :delete, class:"btn btn-danger" %>
    <% else %>
       <%= button_to  'Enroll', enrollment_path(event_id: @event.id), method: :patch, class:"btn btn-dark" %>
    <% end %>
<% end %>

app/views/events/_invites.html.erb
<ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1"">
  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
       Invitees: <%= User.find(@event.enrollments.invited.map {|en_user| en_user.user_id }).count %> <b class="caret"></b>
      </a>
      <% if User.find(@event.enrollments.invited.map {|en_user| en_user.user_id }).any? %>
      <ul class="dropdown-menu">
      <% User.find(@event.enrollments.invited.map { |en_user| en_user.user_id }).each do |user| %>
        <li>
          <%= link_to user.name, users_path %>
        </li>
      <% end %>
      </ul>
      <% end %>
  </li>
</ul>

app/views/events/_link.html.erb
<% if @event.creator == current_user %>
  <%= link_to 'Edit', edit_event_path(@event), class:'text-dark' %><br />
  <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:'text-dark' %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class:'btn btn-light my-2' %> 
<%= link_to 'Back', events_path, class:'btn btn-light my-2' %>

app/views/events/index.html.erb
<div class='row justify-content-between'>
<h2 class='text-center'> Upcoming Events </h2>
<% @upcoming_events.each do |event| %>

<div class="card text-center col-12 col-md-3">
  <div class="card-header">
    <h5 class=""><%= event.name %> </h5>
  </div>
  <div class="card-body">
    <%= link_to 'MORE', event, class:"btn btn-dark" %>
  </div>
  <div class="card-footer text-muted">
    <p>  <%= event.date %> </p>
  </div>
</div>
  <% end %>
</div>

<div class='row justify-content-between'>
<h2 class='text-center'> Past Events </h2>
<% @past_events.each do |event| %>

<div class="card text-center col-12 col-md-3">
  <div class="card-header">
    <h5 class=""><%= event.name %> </h5>
  </div>
  <div class="card-body">
    <%= link_to 'MORE', event, class:"btn btn-dark" %>
  </div>
  <div class="card-footer text-muted">
    <p> <%= event.date %> </p>
  </div>
</div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class:'btn btn-light my-2' %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="card border text-center px-3">

      <div class="card-header">
        <div class="wrap_card">
          <div class="w-100">
          </div>
          <div>
            <h1> <%= @event.name %></h1>
            <hr>

                  <button class="btn btn-dark" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Invitees: <%= User.find(@event.enrollments.invited.map { |enr| enr.user_id }).count %></span>
                  </button>

                    <ul>
                      <% if User.find(@event.enrollments.invited.map { |enr| enr.user_id }).any? %>
                      <div class="dropdown-item">
                        <% User.find(@event.enrollments.invited.map { |enr| enr.user_id }).each do |user| %>
                        <li>
                          <p><%= user.name %></p>
                        </li>
                        <% end %>
                      </div>
                      <% end %>
                    </ul>


                  <button class="btn btn-dark" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Attendies:
                      <%= User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).count %></span>
                  </button>


                    <ul>
                      <% if User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).any? %>
                      <div class="dropdown-item">
                        <% User.find(@event.enrollments.accepted.map { |enr| enr.user_id }).each do |user| %>
                        <li>
                          <p><%= user.name %></p>
                        </li>
                        <% end %>
                      </div>
                      <% end %>
                    </ul>
</div>
        <% if @event.creator == current_user %>
            <%= button_to "Invite", users_path, params: {:event_id => @event.id}, method: :get, class: "btn btn-dark" %>
          <% else %>
            <% enrollment = Enrollment.find_by(event_id: @event.id, user_id: current_user.id) %>
            <% if enrollment && enrollment.accepted? %>
              <%= button_to "Cancel", enrollment_path(id: enrollment.id, event_id: @event.id, user_id: current_user.id), method: :delete, class: "btn btn-dark" %>
            <% else %>
              <%= button_to "Enroll", enrollment_path(event_id: @event.id), method: :patch, class: "btn btn-dark" %>
            <% end %>
          <% end %>


      <div class="card-body">

        <p class="card-text"><%= @event.description %> </p>


        <h5 class="text-right mr-2"> by <%= @event.creator.name %> </h5>
        <hr>
      </div>
      <div class="card-footer text-muted">
        <p class='text-center'> date : <%= @event.date %></p>
      </div>
    </div>
  </div>
</div>

<%= render 'events/link' %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<header class='fixed-top'>
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom container pt-2">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <i class="fas fa-calendar-week fa-2x"></i>
        <span class="fs-3 mx-2">Personal Events</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <%= create_event_btn %>
    <%= current_user_btn %>
      <%= sign_out_btn %>
      <%= sign_up_btn %> 
      <%= log_in_btn %>
      </nav>
    </div>
    </header>

app/views/layouts/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

     <!-- font awesome link -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    <title>Events</title>
  </head>
  <body class="mt-5 pt-5">
      <%= alert_btn %>
      <%= notice_btn %>
    <%= render 'layouts/header'%>

    <div class="container">
    <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6">Guest List</h2>
    
          <div class="columns is-centered">
            <table class="table is-fullwidth is-hoverable">
              <tbody>
                <th class="has-text-centered">Name</th>
                <th class="has-text-centered">Status</th>
                <th class="has-text-centered">Action</th>
                <% @users.reject { |user| user == Event.find(params[:event_id]).creator }.each do |user| %>
                  <% enrollment = Enrollment.find_by(event_id: params[:event_id], user_id: user.id) %>
                  <tr>
                    <td class="has-text-centered">
                      <%= user.name %>
                    </td>
                    <% unless enrollment.nil? || enrollment.status.nil? %>
                      <td class="has-text-centered">
                        <span class="tag is-primary is-medium is-light"><%= enrollment.status %><span>
                      </td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <% if enrollment.nil? %>
                      <td class="has-text-centered">
                        <%= button_to "Invite", enrollments_path(event_id: params[:event_id], user_id: user.id), class: "btn btn-dark" %>
                      </td>
                    <% else %>
                      <td class="has-text-centered">
                        <%= button_to "Cancel Invitation", enrollment_path(id: enrollment.id, event_id: params[:event_id]), method: :delete, class: "btn btn-dark" %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <br/>

          <%= link_to 'Back to Event Details', event_path(id: params[:event_id]), class: "text-dark" %>

        </div>
      </div>
    </div>
  </div>
</div>